name: docs

env:
  CLOUDFLARE_PROJECT_DOXYGEN: doxygen-engine
  CLOUDFLARE_PROJECT_PONG: pong-engine

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  doxygen:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    steps:
      - 
        uses: actions/checkout@master
      - 
        run: |
          docker run --rm -v $(pwd):/app -w /app rodrigodornelles/doxygen:lua lua tools/doxygen_plugins.lua
      - 
        run: |
          docker run --rm -v $(pwd):/app -w /app rodrigodornelles/doxygen:lua doxygen
      - 
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ env.CLOUDFLARE_PROJECT_DOXYGEN }}
          directory: html

  pong:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    steps:
      - 
        uses: actions/checkout@master
      - 
        run: |
          docker run --rm -v $(pwd):/app -w /app rodrigodornelles/doxygen:lua ./cli.sh build --core html5 ./examples/pong/game.lua --dist ./html/
      - 
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ env.CLOUDFLARE_PROJECT_PONG }}
          directory: html
