name: docs

env:
  CLOUDFLARE_PROJECT_DOXYGEN: doxygen-gly
  CLOUDFLARE_PROJECT_EXAMPLE: example-gly

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  doxygen:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    steps:
      - 
        uses: actions/checkout@master
      - 
        run: |
          docker run --rm -v $(pwd):/app -w /app rodrigodornelles/doxygen:lua lua tools/doxygen_plugins.lua
      - 
        run: |
          docker run --rm -v $(pwd):/app -w /app rodrigodornelles/doxygen:lua doxygen
      - 
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'workflow_dispatch'
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ env.CLOUDFLARE_PROJECT_DOXYGEN }}
          directory: html

  example:
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        game: ['asteroids', 'dvdplayer', 'launcher', '2games', 'helloworld', 'gridsystem', 'pong', 'capybird']
    steps:
      - 
        uses: actions/checkout@master
      - 
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: '5.4'
      - 
        run: |
          lua tools/cd_docs_example.lua ${{ matrix.game }}
      - 
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'workflow_dispatch'
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ matrix.game }}-${{ env.CLOUDFLARE_PROJECT_EXAMPLE }}
          directory: html
